import image1 from "./assets/img/image1.jpg"
import image2 from "./assets/img/image2.jpg"
import image3 from "./assets/img/image3.jpg"
import image4 from "./assets/img/image4.jpg"


    export const resepData = [
        {
        id: 1,
        image: image4,
        title: "Scrambled and Fried Eggs",
        video: "UXtrScuC30E?si=GjepuQlryN6tl2Jz",
        description: "ini adalah deskripsi makanan Barat",
        ingredients: ["Telur", "Roti", "Tomat", "Margarin", "Garam", "Lada"],
        steps: ["Siapkan 2 Roti", "Panaskan wajan dan tuangkan olive oil", "Pecahkan Telur dan tuangkan ke wajan","Aduk Telur seperti urak arik"," Beri garam secukupnya","beri lada secukupnya "],
        category: "Telur",
        },
        {
        id: 2,
        image: image2,
        title: "Masakan Tradisional",
        video: "ptW7zemegL8?si=3jUVgkutvP8EfwtZ",
        description: "Ini adalah deskripsi untuk Masakan Tradisional.",
        ingredients: ["Bahan A", "Bahan B", "Bahan C"],
        steps: ["Langkah A", "Langkah B", "Langkah C"],
        category: "Tradisional",
        },
        {
        id: 3,
        image: image3,
        title: "Resep Daging",
        video: "hXdfWJbFnqA?si=wqO17gIGUEZANfu5",
        description: "Ini adalah deskripsi untuk Resep Daging.",
        ingredients: ["Daging 1", "Daging 2", "Daging 3"],
        steps: ["Langkah D1", "Langkah D2", "Langkah D3"],
        category: "Daging",
        },
        {
        id: 4,
        image: image2,
        title: "Resep Ayam Goreng",
        video: "/src/assets/videos/video4.mp4",
        description: "Ini adalah deskripsi untuk Resep Ayam Goreng.",
        ingredients: ["Ayam 1", "Ayam 2", "Ayam 3"],
        steps: ["Langkah A1", "Langkah A2", "Langkah A3"],
        category: "Ayam",
        },
        {
        id: 5,
        image: image3,
        title: "Resep Sayuran",
        video: "/src/assets/videos/video5.mp4",
        description: "Ini adalah deskripsi untuk Resep Sayuran.",
        ingredients: ["Sayur 1", "Sayur 2", "Sayur 3"],
        steps: ["Langkah S1", "Langkah S2", "Langkah S3"],
        category: "Sayuran",
        },
        {
        id: 6,
        image: image1,
        title: "Resep Seafood",
        video: "/src/assets/videos/video6.mp4",
        description: "Ini adalah deskripsi untuk Resep Seafood.",
        ingredients: ["Seafood 1", "Seafood 2", "Seafood 3"],
        steps: ["Langkah F1", "Langkah F2", "Langkah F3"],
        category: "Seafood",
        },
        {
        id: 7,
        image: image3,
        title: "Resep Menu Pagi",
        video: "/src/assets/videos/video7.mp4",
        description: "Ini adalah deskripsi untuk Resep Menu Pagi.",
        ingredients: ["Pagi 1", "Pagi 2", "Pagi 3"],
        steps: ["Langkah P1", "Langkah P2", "Langkah P3"],
        category: "Pagi",
        },
        {
        id: 8,
        image: image1,
        title: "Resep Menu Malam",
        video: "/src/assets/videos/video8.mp4",
        description: "Ini adalah deskripsi untuk Resep Menu Malam.",
        ingredients: ["Malam 1", "Malam 2", "Malam 3"],
        steps: ["Langkah M1", "Langkah M2", "Langkah M3"],
        category: "Malam",
        },
        {
        id: 9,
        image: image2,
        title: "Resep Sarapan",
        video: "/src/assets/videos/video8.mp4",
        description: "Ini adalah deskripsi untuk Resep Menu Sarapan.",
        ingredients: ["Pagi 1", "Pagi 2", "Pagi 3"],
        steps: ["Langkah S1", "Langkah S2", "Langkah S3"],
        category: "Sarapan",
        },
        {
        id: 10,
        image: image3,
        title: "Resep Ngoding",
        video: "/src/assets/videos/video8.mp4",
        description: "Ini adalah deskripsi untuk Resep Menu Coding.",
        ingredients: ["Coding 1", "Coding 2", "Coding 3"],
        steps: ["Langkah C1", "Langkah C2", "Langkah C3"],
        category:"Coding",
        },
        {
        id: 11,
        image: image1,
        title: "Resep Ngoding",
        video: "/src/assets/videos/video8.mp4",
        description: "Ini adalah deskripsi untuk Resep Menu Coding.",
        ingredients: ["Coding 1", "Coding 2", "Coding 3"],
        steps: ["Langkah C1", "Langkah C2", "Langkah C3"],
        category: "Coding",
        },
        {
        id: 12,
        image: image3,
        title: "Resep Ngoding",
        video: "/src/assets/videos/video8.mp4",
        description: "Ini adalah deskripsi untuk Resep Menu Coding.",
        ingredients: ["Coding 1", "Coding 2", "Coding 3"],
        steps: ["Langkah C1", "Langkah C2", "Langkah C3"],
        category: "Coding",
        },
        {
        id: 13,
        image: image1,
        title: "Resep Ngoding",
        video: "/src/assets/videos/video8.mp4",
        description: "Ini adalah deskripsi untuk Resep Menu Coding.",
        ingredients: ["Coding 1", "Coding 2", "Coding 3"],
        steps: ["Langkah C1", "Langkah C2", "Langkah C3"],
        category: "Coding",
        },
    ];